spring:
  application.name: music-calendar
  datasource:
    url: jdbc:postgresql://localhost:5432/musiccalendar_postgres
    username: user
    password: das-passwort
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update

songkick:
  url: https://api.songkick.com
  api-key: api-key